env:
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
  ecmaVersion: 2019 # Node.js 12の場合は2019、他のバージョンのNode.jsを利用している場合は場合は適宜変更する
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - ./node_modules
  - ./dist
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
rules: {}
