env:
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
  ecmaVersion: 2019 # Node.js 12の場合は2019、他のバージョンのNode.jsを利用している場合は場合は適宜変更する
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
ignorePatterns:
  # 除外対象
  - ./node_modules
  - ./dist
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
rules: {
    # 暫定処置 この記述がないとlint が通らない
    # この対応は、別issue
    "@typescript-eslint/no-explicit-any": 0,
    "@typescript-eslint/no-unsafe-argument": 0,
  }
