env:
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  tsconfigRootDir: __dirname
  ecmaVersion: 2019 # Node.js 12の場合は2019、他のバージョンのNode.jsを利用している場合は場合は適宜変更する
plugins:
  - '@typescript-eslint'
extends: 
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
rules: {}
